## Script sample of the view for the monthly M7 Report.

SELECT DISTINCT
PERIOD_START_DATE_KEY,
PERIOD_END_DATE_KEY,
REPORTED_MONTH,
INCIDENT_NUMBER,
DOCUMENTID,
CUSTOMER_NUMBER,
SLA_NAME,
CONTACT_COMPANY,
SERVICE_TYPE_DESCRIPTION,
SERVICE_COMPONENT,
M7_SERVICE_COMPONENT,
SERVICE_CATEGORY,
SERVICE_SUB_CATEGORY,
PRODUCT_NAME,
COMPLIANCE_TARGET,
SLA_CONFIG_DESC,
CHM_CTM_CLUSTER,
ORIGINAL_CHM_CTM_CLUSTER,
SUPPORT_GROUP_FILTER,
LASTATUS,
LASTATUS_DESC,
SIGNED_UNSIGNED,
CONTRACT_STATUS,
[MPSS_CONTRACTTYPE] AS [MPSSCONTRACTTYPE],
[MPSS_STATUS] AS [MPSSSTATUS],
TICKET_MET,
1 AS M7_RESP_TICKET_MET,    --M7_RESP_TICKET_MET,
TICKET_MISSED,
MET_OR_MISSED,
SLM_KEYWORD_UPC,
SLM_KEYWORD_RSP,
SUBMIT_DATE,
RESPONDED_DATE,
LAST_RESOLVED_DATE,
ASSIGNEE,
ESTIMATED_RESOLUTION_DATE,
SOURCE_SYSTEM_CD,
ASSIGNED_GROUP,
HELP_PRIORITY_DESC,
TIME_TAKEN,
MODIFIED_DATE,
TITLE,
TARGETHOURS,
COORDINATOR,
STRUCTURE_LEVEL_1,
STRUCTURE_LEVEL_2,
STRUCTURE_LEVEL_3,
STRUCTURE_LEVEL_4,
CREATE_DT,
BATCH_ID,
M5Previously_Reported_IND,
M5Previously_Reported_Month
,HPD_CI
,WA_NO
,VPN_Type
,ASSIGNED_SUPPORT_COMPANY
,ASSIGNED_SUPPORT_ORGANIZATION

FROM FCT_REPORT_SB_ITSM_LAST_INCIDENT10

WHERE 
REPORTED_MONTH >= 201811
