## usp_FCT_REPORT_SB_ITSM_LAST_INCIDENT10

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD]') AND TYPE IN (N'U'))
DROP TABLE [DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD;

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1]') AND TYPE IN (N'U'))
DROP TABLE [DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1;

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILDY]') AND TYPE IN (N'U'))
DROP TABLE [DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILDY;

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FCT_ASPECT_ITSM_INCIDENT10_BRIDGE_SNAPM_LOAD]') AND TYPE IN (N'U'))
DROP TABLE [DBO].FCT_ASPECT_ITSM_INCIDENT10_BRIDGE_SNAPM_LOAD;

 DECLARE @PERIOD_START_DATE_KEY INT;
 DECLARE @DATE_KEY INT
 DECLARE @REPORTED_MONTH INT;
 DECLARE @DW_BATCH_ID BIGINT;
 
 SET @PERIOD_START_DATE_KEY = CONVERT(VARCHAR(6),GETDATE(),112) + '01';
 SET @DATE_KEY =  CONVERT(VARCHAR(10),GETDATE(),112);--NOTE: Remove the -1 before deploying back to PROD!!!!!
 SET @REPORTED_MONTH = CONVERT(VARCHAR(6),GETDATE(),112);
 SET @DW_BATCH_ID = (NEXT VALUE FOR [BiAuditLayer].[dbo].[SEQ_BATCH_ID]);


DELETE FROM BIExploitationLayer.[DBO].FCT_REPORT_SB_ITSM_LAST_INCIDENT10
WHERE REPORTED_MONTH = @REPORTED_MONTH
AND SOURCE_SYSTEM_CD='ITSM';



---------------------------------------------------------------------------------------

BEGIN TRY

 INSERT INTO BIAUDITLAYER.[dbo].[DW_AUDIT_TRAIL]
 SELECT @DW_BATCH_ID AS BATCH_ID, 
        'ExploitationDailyLoads ITSM_LAST_INCIDENT10','BiExploitationLayer',
  GETDATE() AS LOAD_START_DT,
  NULL AS LOAD_END_DT,
  'N' AS LOAD_FINISHED,
  'Starting with Load - FCT_REPORT_SB_ITSM_LAST_INCIDENT10' AS MESSAGE_TRAIL,
  NULL AS RECORD_COUNT,
  GETDATE() AS CREATE_DT;

---------------------------------------------------------------------------------------
--ALGORITHM STEP 1: Create TMP..LOAD table that contains only the relevant Reported_Month from IncidentBridge table as a subset (to optimise processing time)
SELECT 
       [PERIOD_START_DATE_KEY]
      ,[PERIOD_END_DATE_KEY]
      ,[REPORTED_MONTH]
      ,[CONTACT_COMPANY]
      ,[ASSIGNED_GROUP]
      ,[SERVICE_COMPONENT]
      ,[MPSS_SLM_KEYWORD]
      ,[NEWSIGNEDDTE]
      ,[NEWENDDTE]
      ,[NEWSTARTDTE]
      ,[TDJ_SLA_CONFIG]
      ,[TDJ_SLA_CONFIG_DESC]
      ,[SERVICE_CATEGORY]
      ,[SERVICE_SUB_CATEGORY]
      ,[M7_SERVICE_COMPONENT]
      ,[TDJ_COMPLIANCE]
      ,[DOCUMENTID]
      ,[CUSTOMER_NUMBER]
      ,[PRODUCT_NAME]
      ,[CONTRACT_SIGNED_STATUS]
      ,[CONTRACT_STATUS]
      ,[MPSS_STATUS]
      ,[MPSS_CONTRACTTYPE]
      ,[CONTRACT_STATUS_DESC]
      ,[CONTRACT_STATUS_GROUP]
      ,[BATCH_ID]
      ,[CREATE_DT]
INTO [DBO].FCT_ASPECT_ITSM_INCIDENT10_BRIDGE_SNAPM_LOAD
FROM [BIExploitationLayer].[dbo].[FCT_ASPECT_ITSM_INCIDENT_BRIDGE_SNAPM]
WHERE REPORTED_MONTH = @REPORTED_MONTH;


----ALGORITHM STEP 2: Insert into [TMP_SB_REPORT_...FinalBuild] 
/*Subset 1: From TEAMMEASUREMENT_COMBO all entries where 
		a) Source System = ITSM
		b) Opening/Closing Product is NOT null or NOT 'Unknown'
		*/
SET STATISTICS IO, TIME OFF;

SELECT DISTINCT                 
A.PERIOD_START_DATE_KEY,
A.PERIOD_END_DATE_KEY,
A.REPORTED_MONTH,
A.INCIDENT_NUMBER,

CASE 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[Signed_Date] IS NOT NULL THEN 'Signed' 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[Signed_Date] IS NULL THEN 'Unsigned'
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
END AS [SIGNED_UNSIGNED],

CASE 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[ContractStatus] IN (0,1,2,3) THEN CTR.[ContractStatus] 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[ContractStatus] NOT IN (0,1,2,3) THEN -1 
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
END AS CONTRACT_STATUS,

NULL AS [MPSS_CONTRACTTYPE],
NULL AS [MPSS_STATUS],


CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.DOCUMENTID END AS DOCUMENTID,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.CUSTOMER_NUMBER END AS CUSTOMER_NUMBER,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.M7_SERVICE_COMPONENT END AS M7_SERVICE_COMPONENT,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.SERVICE_CATEGORY END AS SERVICE_CATEGORY,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.SERVICE_SUB_CATEGORY END AS SERVICE_SUB_CATEGORY,

CASE 
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND E.[ASSIGNED_GROUP] LIKE '%DBE%' THEN COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME)
ELSE G.PRODUCT_NAME
END AS PRODUCT_NAME,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_COMPLIANCE END AS COMPLIANCE_TARGET,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_SLA_CONFIG END AS TDJ_SLA_CONFIG,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_SLA_CONFIG_DESC END AS TDJ_SLA_CONFIG_DESC,

B.SLA_NAME,
C.COMPANY AS CONTACT_COMPANY,
D.SERVICE_TYPE,
D.SERVICE_TYPE_DESCRIPTION,
F.SERVICECI AS SERVICE_COMPONENT,  
C.CHM_CTM_CLUSTER,
C.ORIGINAL_CHM_CTM_CLUSTER,
E.SUPPORT_GROUP_FILTER,
J.LASTATUS_CD AS LASTATUS,
J.LASTATUS_DESC,
A.TICKET_MET,
A.TICKET_MISSED,
A.MET_OR_MISSED,
A.SLM_KEYWORD_SLA,
A.SLM_KEYWORD_OLA,
A.SLM_KEYWORD_UPC,
A.SLM_KEYWORD_RSP,
A.SUBMIT_DATE,
A.RESPONDED_DATE,
A.LAST_RESOLVED_DATE,
A.PARENTTOTALELAPSEDTIME,
A.PENDINGTIME,
A.ASSIGNEE,
[BiExploitationLayer].dbo.[convertUnixDate](A.ESTIMATED_RESOLUTION_DATE) AS ESTIMATED_RESOLUTION_DATE,
K.SOURCE_SYSTEM_CD,
ISNULL(E.ASSIGNED_GROUP,G.ASSIGNED_GROUP) AS ASSIGNED_GROUP,
Z.PRIORITY_CD,
Z.HELP_PRIORITY_DESC,
A.TIME_TAKEN,
A.MODIFIED_DATE,
X.TITLE,
X.TARGETHOURS,
E.COORDINATOR,
E.STRUCTURE_LEVEL_1,
E.STRUCTURE_LEVEL_2,
E.STRUCTURE_LEVEL_3,
E.STRUCTURE_LEVEL_4,
'N' as M5Previously_Reported_IND,
NULL as M5Previously_Reported_Month,
A.HPD_CI,
A.ASSIGNED_SUPPORT_COMPANY,
A.ASSIGNED_SUPPORT_ORGANIZATION

INTO  BIExploitationLayer.[DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD
	
FROM [BIExploitationLayer].[dbo].[FCT_ITSM_HELPDESK_TEAMMEASUREMENT_COMBO_SNAPM] A 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SLA B ON A.SLA_KEY = B.SLA_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_COMPANY_CLIENT C ON A.COMPANY_CLIENT_KEY = C.COMPANY_CLIENT_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SERVICE_TYPE D ON A.SERVICE_TYPE_KEY = D.SERVICE_TYPE_KEY 
INNER JOIN 
[BiExploitationLayer].DBO.VW_DIM_ASSIGNED_SUPPORT_GROUP E ON A.ASSIGNED_GROUP_KEY = E.ASSIGNED_GROUP_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SERVICECI F ON A.SERVICECI_KEY = F.SERVICECI_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_INCIDENT_STATUS J ON A.INCIDENT_STATUS_KEY = J.INCIDENT_STATUS_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRODUCT W ON A.OPENING_PRODUCT_KEY = W.PRODUCT_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRODUCT T ON A.CLOSING_PRODUCT_KEY = T.PRODUCT_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_SOURCE_SYSTEM K ON A.SOURCE_SYSTEM_KEY = K.SOURCE_SYSTEM_KEY 

LEFT OUTER JOIN
(
	SELECT DISTINCT 
	CONTACT_COMPANY, 
	MPSS_SLM_KEYWORD,   
	DOCUMENTID,
	CUSTOMER_NUMBER,
	SERVICE_COMPONENT, 
	M7_SERVICE_COMPONENT,
	SERVICE_CATEGORY,
	SERVICE_SUB_CATEGORY,
	TDJ_COMPLIANCE,
	TDJ_SLA_CONFIG,
	TDJ_SLA_CONFIG_DESC,
	ASSIGNED_GROUP,
	PRODUCT_NAME
	FROM [BIExploitationLayer].DBO.FCT_ASPECT_ITSM_INCIDENT10_BRIDGE_SNAPM_LOAD
) G 
	ON C.COMPANY = G.CONTACT_COMPANY 
	AND F.SERVICECI = G.SERVICE_COMPONENT 
	AND ISNULL(E.ASSIGNED_GROUP,'A') = CASE 
										WHEN ISNULL(G.ASSIGNED_GROUP,'A') = 'A' 
										THEN 'A' 
										ELSE G.ASSIGNED_GROUP END

AND COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME) = ISNULL(G.PRODUCT_NAME,COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME))

LEFT JOIN [BiLandingLayer].[dbo].[vw_SRC_SLM_Contract_AllLatest] CTR 
	ON CTR.Project_Number = G.DOCUMENTID 
AND CTR.DATE_KEY = @DATE_KEY

INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRIORITY_STATUS Z ON A.PRIORITY_STATUS_KEY = Z.PRIORITY_STATUS_KEY 
LEFT OUTER JOIN
(SELECT DISTINCT TITLE, TARGETHOURS FROM BISTAGINGLAYER.DBO.STG_ITSM_INCIDENT_BUILD) X ON B.SLA_Name = X.TITLE

WHERE A.PERIOD_START_DATE_KEY = @PERIOD_START_DATE_KEY
AND B.SLA_Name LIKE '%M7%'
--AND K.SOURCE_SYSTEM_CD NOT IN ('AGRI','DEFE','TRAN','SAPS')
AND K.SOURCE_SYSTEM_CD IN ('ITSM')
AND COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME) IS NOT NULL
AND COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME) <> 'Unknown'

UNION 

----ALGORITHM STEP 3: Insert into [TMP_SB_REPORT_...FinalBuild] 
/*Subset 2: From TEAMMEASUREMENT_COMBO all entries where 
		a) Source System = ITSM
		b) Opening/Closing Product IS null or IS 'Unknown'
		*/
SELECT DISTINCT                 
A.PERIOD_START_DATE_KEY,
A.PERIOD_END_DATE_KEY,
A.REPORTED_MONTH,
A.INCIDENT_NUMBER,

CASE 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[Signed_Date] IS NOT NULL THEN 'Signed' 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[Signed_Date] IS NULL THEN 'Unsigned'
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
END AS [SIGNED_UNSIGNED],

CASE 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[ContractStatus] IN (0,1,2,3) THEN CTR.[ContractStatus] 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND CTR.[ContractStatus] NOT IN (0,1,2,3) THEN -1 
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
END AS CONTRACT_STATUS,

NULL AS [MPSS_CONTRACTTYPE],
NULL AS [MPSS_STATUS],

CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.DOCUMENTID END AS DOCUMENTID,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.CUSTOMER_NUMBER END AS CUSTOMER_NUMBER,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.M7_SERVICE_COMPONENT END AS M7_SERVICE_COMPONENT,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.SERVICE_CATEGORY END AS SERVICE_CATEGORY,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.SERVICE_SUB_CATEGORY END AS SERVICE_SUB_CATEGORY,

CASE 
WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL 
WHEN B.SLA_NAME NOT LIKE '%Generic%' AND E.[ASSIGNED_GROUP] LIKE '%DBE%' THEN COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME)
ELSE G.PRODUCT_NAME
END AS PRODUCT_NAME,

CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_COMPLIANCE END AS COMPLIANCE_TARGET,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_SLA_CONFIG END AS TDJ_SLA_CONFIG,
CASE WHEN B.SLA_NAME LIKE '%Generic%' THEN NULL ELSE G.TDJ_SLA_CONFIG_DESC END AS TDJ_SLA_CONFIG_DESC,

B.SLA_NAME,
C.COMPANY AS CONTACT_COMPANY,
D.SERVICE_TYPE,
D.SERVICE_TYPE_DESCRIPTION,
F.SERVICECI AS SERVICE_COMPONENT, 
C.CHM_CTM_CLUSTER,
C.ORIGINAL_CHM_CTM_CLUSTER,
E.SUPPORT_GROUP_FILTER,
J.LASTATUS_CD AS LASTATUS,
J.LASTATUS_DESC,
A.TICKET_MET,
A.TICKET_MISSED,
A.MET_OR_MISSED,
A.SLM_KEYWORD_SLA,
A.SLM_KEYWORD_OLA,
A.SLM_KEYWORD_UPC,
A.SLM_KEYWORD_RSP,
A.SUBMIT_DATE,
A.RESPONDED_DATE,
A.LAST_RESOLVED_DATE,
A.PARENTTOTALELAPSEDTIME,
A.PENDINGTIME,
A.ASSIGNEE,
[BiExploitationLayer].dbo.[convertUnixDate](A.ESTIMATED_RESOLUTION_DATE) AS ESTIMATED_RESOLUTION_DATE,
K.SOURCE_SYSTEM_CD,
ISNULL(E.ASSIGNED_GROUP,G.ASSIGNED_GROUP) AS ASSIGNED_GROUP,
Z.PRIORITY_CD,
Z.HELP_PRIORITY_DESC,
A.TIME_TAKEN,
A.MODIFIED_DATE,
X.TITLE,
X.TARGETHOURS,
E.COORDINATOR,
E.STRUCTURE_LEVEL_1,
E.STRUCTURE_LEVEL_2,
E.STRUCTURE_LEVEL_3,
E.STRUCTURE_LEVEL_4,
'N' as M5Previously_Reported_IND,
NULL as M5Previously_Reported_Month,
A.HPD_CI,
A.ASSIGNED_SUPPORT_COMPANY,
A.ASSIGNED_SUPPORT_ORGANIZATION

FROM [BIExploitationLayer].[dbo].[FCT_ITSM_HELPDESK_TEAMMEASUREMENT_COMBO_SNAPM] A 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SLA B ON A.SLA_KEY = B.SLA_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_COMPANY_CLIENT C ON A.COMPANY_CLIENT_KEY = C.COMPANY_CLIENT_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SERVICE_TYPE D ON A.SERVICE_TYPE_KEY = D.SERVICE_TYPE_KEY 
INNER JOIN 
[BiExploitationLayer].DBO.VW_DIM_ASSIGNED_SUPPORT_GROUP E ON A.ASSIGNED_GROUP_KEY = E.ASSIGNED_GROUP_KEY 
INNER JOIN
[BiExploitationLayer].DBO.DIM_SERVICECI F ON A.SERVICECI_KEY = F.SERVICECI_KEY D 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_INCIDENT_STATUS J ON A.INCIDENT_STATUS_KEY = J.INCIDENT_STATUS_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRODUCT W ON A.OPENING_PRODUCT_KEY = W.PRODUCT_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRODUCT T ON A.CLOSING_PRODUCT_KEY = T.PRODUCT_KEY 
INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_SOURCE_SYSTEM K ON A.SOURCE_SYSTEM_KEY = K.SOURCE_SYSTEM_KEY 
LEFT OUTER JOIN
(
SELECT DISTINCT 
CONTACT_COMPANY, 
MPSS_SLM_KEYWORD,   
DOCUMENTID,
CUSTOMER_NUMBER,
SERVICE_COMPONENT, 
M7_SERVICE_COMPONENT,
SERVICE_CATEGORY,
SERVICE_SUB_CATEGORY,
TDJ_COMPLIANCE,
TDJ_SLA_CONFIG,
TDJ_SLA_CONFIG_DESC,
ASSIGNED_GROUP,
PRODUCT_NAME

FROM [BIExploitationLayer].DBO.FCT_ASPECT_ITSM_INCIDENT10_BRIDGE_SNAPM_LOAD
) G ON C.COMPANY = G.CONTACT_COMPANY 
AND F.SERVICECI = G.SERVICE_COMPONENT 
AND ISNULL(E.ASSIGNED_GROUP,'A') = CASE WHEN ISNULL(G.ASSIGNED_GROUP,'A') = 'A' THEN 'A' ELSE G.ASSIGNED_GROUP END 
LEFT JOIN [BiLandingLayer].[dbo].[vw_SRC_SLM_Contract_AllLatest] CTR ON CTR.Project_Number = G.DOCUMENTID 
AND CTR.DATE_KEY = @DATE_KEY

INNER JOIN
BIEXPLOITATIONLAYER.DBO.DIM_PRIORITY_STATUS Z ON A.PRIORITY_STATUS_KEY = Z.PRIORITY_STATUS_KEY 
LEFT OUTER JOIN
(SELECT DISTINCT TITLE, TARGETHOURS FROM BISTAGINGLAYER.DBO.STG_ITSM_INCIDENT_BUILD) X ON B.SLA_Name = X.TITLE

WHERE A.PERIOD_START_DATE_KEY = @PERIOD_START_DATE_KEY
AND B.SLA_Name LIKE '%M7%'
--AND K.SOURCE_SYSTEM_CD NOT IN ('AGRI','DEFE','TRAN','SAPS')
AND K.SOURCE_SYSTEM_CD IN ('ITSM')
AND (COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME) IS NULL OR COALESCE(W.PRODUCT_NAME,T.PRODUCT_NAME) = 'Unknown')


----ALGORITHM STEP 4: Insert into [TMP_SB_REPORT_...FinalBuildY] to lookup Incidents that were previously reported on:


SELECT DISTINCT 
A.INCIDENT_NUMBER, A.DOCUMENTID,
MAX(B.REPORTED_MONTH) as M5Previously_Reported_Month
INTO BIExploitationLayer.[DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILDY
FROM BIExploitationLayer.[DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD A
JOIN BIExploitationLayer.DBO.VW_SB_ITSM_LAST_INCIDENT B ON 
A.INCIDENT_NUMBER = B.INCIDENT_NUMBER
AND ISNULL(A.DOCUMENTID,'A') = ISNULL(B.DOCUMENTID,'A')
WHERE A.REPORTED_MONTH = @REPORTED_MONTH
AND B.REPORTED_MONTH < @REPORTED_MONTH
AND B.MET_OR_MISSED = 'Missed'
Group by A.INCIDENT_NUMBER, A.DOCUMENTID;

----ALGORITHM STEP 5: DELETE from [TMP_SB_REPORT_...FinalBuild] all Incidents that were previously reported on (from BUILDY:
--Yolanda 20200623 This step was changed to NOT DELETE anymore but rather update indicative flags
UPDATE BIExploitationLayer.dbo.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD
	SET
	M5Previously_Reported_IND= 'Y',
	M5Previously_Reported_Month = b.M5Previously_Reported_Month
FROM BIExploitationLayer.dbo.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD a
INNER join BIExploitationLayer.[DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILDY b
on A.Incident_Number=b.Incident_Number
	and a.DOCUMENTID=b.DOCUMENTID;

--  *** Business Rule: Incidents reported on previous 'REPORTED_MONTH's WHERE B.MET_OR_MISSED = 'Missed' , are excluded 

------------------------------
--End of Algorithm STEP 4 & 5--
------------------------------

----------------------------------------------------------------
----Algorithm Step 6: Rank from TMP_...FinalBuild - This is first step to deduplicate for LastIncident
WITH AA AS
(
 SELECT PERIOD_START_DATE_KEY,
	PERIOD_END_DATE_KEY,
	REPORTED_MONTH,
	INCIDENT_NUMBER,
	DOCUMENTID,
	CUSTOMER_NUMBER,
	SLA_NAME,
	CONTACT_COMPANY,
	SERVICE_TYPE,
	SERVICE_TYPE_DESCRIPTION,
    SERVICE_COMPONENT,
	M7_SERVICE_COMPONENT,
	SERVICE_CATEGORY,
	SERVICE_SUB_CATEGORY,
	PRODUCT_NAME,
	COMPLIANCE_TARGET,
	TDJ_SLA_CONFIG,
	TDJ_SLA_CONFIG_DESC,
	CHM_CTM_CLUSTER,
	ORIGINAL_CHM_CTM_CLUSTER,
	SUPPORT_GROUP_FILTER,
	LASTATUS,
	LASTATUS_DESC,
	SIGNED_UNSIGNED,
	CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	TICKET_MET,
	TICKET_MISSED,
	MET_OR_MISSED,
	SLM_KEYWORD_SLA,
	SLM_KEYWORD_OLA,
	SLM_KEYWORD_UPC,
	SLM_KEYWORD_RSP,
	SUBMIT_DATE,
	RESPONDED_DATE,
	LAST_RESOLVED_DATE,
	PARENTTOTALELAPSEDTIME,
	PENDINGTIME,
	ASSIGNEE,
	ESTIMATED_RESOLUTION_DATE,
	SOURCE_SYSTEM_CD,
	ASSIGNED_GROUP,
	PRIORITY_CD,
	HELP_PRIORITY_DESC,
	TIME_TAKEN,
	MODIFIED_DATE,
	TITLE,
	TARGETHOURS, 
	COORDINATOR,
	STRUCTURE_LEVEL_1,
	STRUCTURE_LEVEL_2,
	STRUCTURE_LEVEL_3,
	STRUCTURE_LEVEL_4,	
M5Previously_Reported_IND,
M5Previously_Reported_Month,
HPD_CI,
ASSIGNED_SUPPORT_COMPANY,
ASSIGNED_SUPPORT_ORGANIZATION,
   
	DENSE_RANK() OVER (PARTITION BY REPORTED_MONTH, INCIDENT_NUMBER, [SLM_KEYWORD_RSP], [SLA_NAME] ORDER BY  MODIFIED_DATE DESC) AS RANKING
 FROM BIExploitationLayer.[DBO].TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD
 WHERE CONVERT(VARCHAR(6),MODIFIED_DATE,112) =REPORTED_MONTH   -- (TEAMMEASUREMENT: MODIFIED_DATE)
   AND REPORTED_MONTH = @REPORTED_MONTH
   --  *** Business Rule: The modified date of the incident needs to be in the REPORTED_MONTH

)

----Algorithm Step 7: Select from the Ranked "WITH AA" step 6 data into TMP_...BUILD1 only relevant records where Ranking=1:
/* This is 2nd  step to deduplicate for LastIncident*/
SELECT DISTINCT 
    PERIOD_START_DATE_KEY,
	PERIOD_END_DATE_KEY,
	REPORTED_MONTH,
	INCIDENT_NUMBER,
	DOCUMENTID,
	CUSTOMER_NUMBER,
	SLA_NAME,
	CONTACT_COMPANY,
	SERVICE_TYPE,
	SERVICE_TYPE_DESCRIPTION,
    SERVICE_COMPONENT,
	M7_SERVICE_COMPONENT,
	SERVICE_CATEGORY,
	SERVICE_SUB_CATEGORY,
	PRODUCT_NAME,
	COMPLIANCE_TARGET,
	TDJ_SLA_CONFIG,
	TDJ_SLA_CONFIG_DESC,
	CHM_CTM_CLUSTER,
	ORIGINAL_CHM_CTM_CLUSTER,
	SUPPORT_GROUP_FILTER,
	LASTATUS,
	LASTATUS_DESC,
	SIGNED_UNSIGNED,
	CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	TICKET_MET,
	TICKET_MISSED,
	MET_OR_MISSED,
	SLM_KEYWORD_SLA,
	SLM_KEYWORD_OLA,
	SLM_KEYWORD_UPC,
	SLM_KEYWORD_RSP,
	SUBMIT_DATE,
	RESPONDED_DATE,
	LAST_RESOLVED_DATE,
	PARENTTOTALELAPSEDTIME,
	PENDINGTIME,
	ASSIGNEE,
	ESTIMATED_RESOLUTION_DATE,
	SOURCE_SYSTEM_CD,
	ASSIGNED_GROUP,
	PRIORITY_CD,
	HELP_PRIORITY_DESC,
	TIME_TAKEN,
	MODIFIED_DATE,
	TITLE,
	TARGETHOURS,
	COORDINATOR,
	STRUCTURE_LEVEL_1,
	STRUCTURE_LEVEL_2,
	STRUCTURE_LEVEL_3,
	STRUCTURE_LEVEL_4,
	M5Previously_Reported_IND,
M5Previously_Reported_Month,
HPD_CI,
ASSIGNED_SUPPORT_COMPANY,
ASSIGNED_SUPPORT_ORGANIZATION

INTO BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1
FROM AA
WHERE RANKING = 1;

----STEP 8: Select first patch of deduped data from Build 1 into the final report table
/*DATA SubSet 1: All records for which there are only 2 or less entries in the Build 1 table, assuming 1 for "Reso" keyword and 1 for "Resp" keyword.*/

INSERT INTO BIExploitationLayer.[DBO].FCT_REPORT_SB_ITSM_LAST_INCIDENT10

SELECT DISTINCT  
    A.PERIOD_START_DATE_KEY,
	A.PERIOD_END_DATE_KEY,
	A.REPORTED_MONTH,
	A.INCIDENT_NUMBER,
	A.DOCUMENTID,
	A.CUSTOMER_NUMBER,
	A.SLA_NAME,
	A.CONTACT_COMPANY,
	A.SERVICE_TYPE,
	A.SERVICE_TYPE_DESCRIPTION,
    A.SERVICE_COMPONENT,
	A.M7_SERVICE_COMPONENT,
	A.SERVICE_CATEGORY,
	A.SERVICE_SUB_CATEGORY,
	A.PRODUCT_NAME,
	A.COMPLIANCE_TARGET,
	A.TDJ_SLA_CONFIG,
	A.TDJ_SLA_CONFIG_DESC,
	A.CHM_CTM_CLUSTER,
	A.ORIGINAL_CHM_CTM_CLUSTER,
	A.SUPPORT_GROUP_FILTER,
	A.LASTATUS,
	A.LASTATUS_DESC,
	A.SIGNED_UNSIGNED,
	A.CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	A.TICKET_MET,
	1 AS M7_RESP_TICKET_MET,
	A.TICKET_MISSED,
	A.MET_OR_MISSED,
	A.SLM_KEYWORD_SLA,
	A.SLM_KEYWORD_OLA,
	A.SLM_KEYWORD_UPC,
	A.SLM_KEYWORD_RSP,
	A.SUBMIT_DATE,
	A.RESPONDED_DATE,
	A.LAST_RESOLVED_DATE,
	A.PARENTTOTALELAPSEDTIME,
	A.PENDINGTIME,
	A.ASSIGNEE,
	A.ESTIMATED_RESOLUTION_DATE,
	A.SOURCE_SYSTEM_CD,
	A.ASSIGNED_GROUP,
	A.PRIORITY_CD,
	A.HELP_PRIORITY_DESC,
	A.TIME_TAKEN,
	A.MODIFIED_DATE,
	A.TITLE,
	A.TARGETHOURS,
	@DW_BATCH_ID AS BATCH_ID,
	GETDATE() AS CREATE_DT,
	A.COORDINATOR,
	A.STRUCTURE_LEVEL_1,
	A.STRUCTURE_LEVEL_2,
	A.STRUCTURE_LEVEL_3,
	A.STRUCTURE_LEVEL_4,
    NULL AS [NEWSTARTDTE],
    NULL AS [NEWENDDTE],
    NULL AS [NEWSIGNEDDTE],
M5Previously_Reported_IND,
M5Previously_Reported_Month,
A.HPD_CI,
st.WA_NO,
st.VPN_Type,
  A.ASSIGNED_SUPPORT_COMPANY,
  A.ASSIGNED_SUPPORT_ORGANIZATION

FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1 A
left JOIN [ZWSMCDBCLS01P01_CFI].ARSystem.dbo.GOV_CFG st ON A.HPD_CI = st.End_Address
JOIN 
(
SELECT INCIDENT_NUMBER, REPORTED_MONTH, COUNT(*) CNT
		FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1
	WHERE REPORTED_MONTH = @REPORTED_MONTH
	GROUP BY INCIDENT_NUMBER, REPORTED_MONTH
	HAVING COUNT(*) <= 2) B ON A.REPORTED_MONTH = B.REPORTED_MONTH AND A.INCIDENT_NUMBER = B.INCIDENT_NUMBER
WHERE A.REPORTED_MONTH = @REPORTED_MONTH

----ALGORITHM STEP 9: Select first patch of deduped data from Build 1 into the final report table
/*DATA SubSet 2: All records for which there are more than 2 entries in the Build 1 table, Finding the most recent version where TITLE like "Reso"*/

UNION ALL

--  (PART2: TITLE LIKE '%Reso%')

SELECT DISTINCT 
    AA.PERIOD_START_DATE_KEY,
	AA.PERIOD_END_DATE_KEY,
	AA.REPORTED_MONTH,
	AA.INCIDENT_NUMBER,
	AA.DOCUMENTID,
	AA.CUSTOMER_NUMBER,
	AA.SLA_NAME,
	AA.CONTACT_COMPANY,
	AA.SERVICE_TYPE,
	AA.SERVICE_TYPE_DESCRIPTION,
    AA.SERVICE_COMPONENT,
	AA.M7_SERVICE_COMPONENT,
	AA.SERVICE_CATEGORY,
	AA.SERVICE_SUB_CATEGORY,
	AA.PRODUCT_NAME,
	AA.COMPLIANCE_TARGET,
	AA.TDJ_SLA_CONFIG,
	AA.TDJ_SLA_CONFIG_DESC,
	AA.CHM_CTM_CLUSTER,
	AA.ORIGINAL_CHM_CTM_CLUSTER,
	AA.SUPPORT_GROUP_FILTER,
	AA.LASTATUS,
	AA.LASTATUS_DESC,
	AA.SIGNED_UNSIGNED,
	AA.CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	AA.TICKET_MET,
	1 AS M7_RESP_TICKET_MET,
	AA.TICKET_MISSED,
	AA.MET_OR_MISSED,
	AA.SLM_KEYWORD_SLA,
	AA.SLM_KEYWORD_OLA,
	AA.SLM_KEYWORD_UPC,
	AA.SLM_KEYWORD_RSP,
	AA.SUBMIT_DATE,
	AA.RESPONDED_DATE,
	AA.LAST_RESOLVED_DATE,
	AA.PARENTTOTALELAPSEDTIME,
	AA.PENDINGTIME,
	AA.ASSIGNEE,
	AA.ESTIMATED_RESOLUTION_DATE,
	AA.SOURCE_SYSTEM_CD,
	AA.ASSIGNED_GROUP,
	AA.PRIORITY_CD,
	AA.HELP_PRIORITY_DESC,
	AA.TIME_TAKEN,
	AA.MODIFIED_DATE,
	AA.TITLE,
	AA.TARGETHOURS,
	@DW_BATCH_ID AS BATCH_ID,
	GETDATE() AS CREATE_DT,
	AA.COORDINATOR,
	AA.STRUCTURE_LEVEL_1,
	AA.STRUCTURE_LEVEL_2,
	AA.STRUCTURE_LEVEL_3,
	AA.STRUCTURE_LEVEL_4,
    NULL AS [NEWSTARTDTE],
    NULL AS [NEWENDDTE],
    NULL AS [NEWSIGNEDDTE],
	AA.M5Previously_Reported_IND,
	AA.M5Previously_Reported_Month,
	AA.HPD_CI,
	st.WA_NO,
	st.VPN_Type,
	AA.ASSIGNED_SUPPORT_COMPANY,
	AA.ASSIGNED_SUPPORT_ORGANIZATION


FROM (
SELECT A.*,
DENSE_RANK() OVER (PARTITION BY A.REPORTED_MONTH, A.INCIDENT_NUMBER ORDER BY A.MODIFIED_DATE DESC) AS RANKING
FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1 A,
     (SELECT INCIDENT_NUMBER, REPORTED_MONTH, COUNT(*) CNT
		FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1
	WHERE REPORTED_MONTH = @REPORTED_MONTH
	GROUP BY INCIDENT_NUMBER, REPORTED_MONTH
	HAVING COUNT(*) > 2) B
WHERE A.REPORTED_MONTH = @REPORTED_MONTH
AND A.TITLE LIKE '%Reso%'
AND A.INCIDENT_NUMBER = B.INCIDENT_NUMBER
AND A.REPORTED_MONTH = B.REPORTED_MONTH
) AA

left JOIN [ZWSMCDBCLS01P01_CFI].ARSystem.dbo.GOV_CFG st ON AA.HPD_CI = st.End_Address
WHERE RANKING = 1

----ALGORITHM STEP 10: Select first patch of deduped data from Build 1 into the final report table
/*DATA SubSet 3: All records for which there are more than 2 entries in the Build 1 table, Finding the most recent version where TITLE like "Resp"*/

UNION ALL

--  (PART3: TITLE LIKE '%Resp%')

SELECT DISTINCT 
    AA.PERIOD_START_DATE_KEY,
	AA.PERIOD_END_DATE_KEY,
	AA.REPORTED_MONTH,
	AA.INCIDENT_NUMBER,
	AA.DOCUMENTID,
	AA.CUSTOMER_NUMBER,
	AA.SLA_NAME,
	AA.CONTACT_COMPANY,
	AA.SERVICE_TYPE,
	AA.SERVICE_TYPE_DESCRIPTION,
    AA.SERVICE_COMPONENT,
	AA.M7_SERVICE_COMPONENT,
	AA.SERVICE_CATEGORY,
	AA.SERVICE_SUB_CATEGORY,
	AA.PRODUCT_NAME,
	AA.COMPLIANCE_TARGET,
	AA.TDJ_SLA_CONFIG,
	AA.TDJ_SLA_CONFIG_DESC,
	AA.CHM_CTM_CLUSTER,
	AA.ORIGINAL_CHM_CTM_CLUSTER,
	AA.SUPPORT_GROUP_FILTER,
	AA.LASTATUS,
	AA.LASTATUS_DESC,
	AA.SIGNED_UNSIGNED,
	AA.CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	AA.TICKET_MET,
	1 AS M7_RESP_TICKET_MET,
	AA.TICKET_MISSED,
	AA.MET_OR_MISSED,
	AA.SLM_KEYWORD_SLA,
	AA.SLM_KEYWORD_OLA,
	AA.SLM_KEYWORD_UPC,
	AA.SLM_KEYWORD_RSP,
	AA.SUBMIT_DATE,
	AA.RESPONDED_DATE,
	AA.LAST_RESOLVED_DATE,
	AA.PARENTTOTALELAPSEDTIME,
	AA.PENDINGTIME,
	AA.ASSIGNEE,
	AA.ESTIMATED_RESOLUTION_DATE,
	AA.SOURCE_SYSTEM_CD,
	AA.ASSIGNED_GROUP,
	AA.PRIORITY_CD,
	AA.HELP_PRIORITY_DESC,
	AA.TIME_TAKEN,
	AA.MODIFIED_DATE,
	AA.TITLE,
	AA.TARGETHOURS,
	@DW_BATCH_ID AS BATCH_ID,
	GETDATE() AS CREATE_DT,
	AA.COORDINATOR,
	AA.STRUCTURE_LEVEL_1,
	AA.STRUCTURE_LEVEL_2,
	AA.STRUCTURE_LEVEL_3,
	AA.STRUCTURE_LEVEL_4,
    NULL AS [NEWSTARTDTE],
    NULL AS [NEWENDDTE],
    NULL AS [NEWSIGNEDDTE],
M5Previously_Reported_IND,
M5Previously_Reported_Month,
HPD_CI,
st.WA_NO,
st.VPN_Type,
AA.ASSIGNED_SUPPORT_COMPANY,
AA.ASSIGNED_SUPPORT_ORGANIZATION

FROM (
SELECT A.*,
DENSE_RANK() OVER (PARTITION BY A.REPORTED_MONTH, A.INCIDENT_NUMBER ORDER BY A.MODIFIED_DATE DESC) AS RANKING
FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1 A,
     (SELECT INCIDENT_NUMBER, REPORTED_MONTH, COUNT(*) CNT
		FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1
	WHERE REPORTED_MONTH = @REPORTED_MONTH
	GROUP BY INCIDENT_NUMBER, REPORTED_MONTH
	HAVING COUNT(*) > 2) B
WHERE A.REPORTED_MONTH = @REPORTED_MONTH
AND A.TITLE LIKE '%Resp%'
AND A.INCIDENT_NUMBER = B.INCIDENT_NUMBER
AND A.REPORTED_MONTH = B.REPORTED_MONTH
) AA
left JOIN [ZWSMCDBCLS01P01_CFI].ARSystem.dbo.GOV_CFG st ON AA.HPD_CI = st.End_Address
WHERE RANKING =1


UNION ALL

--  (PART3: TITLE LIKE '%M7%' for more than 2 entries)

SELECT DISTINCT 
    AA.PERIOD_START_DATE_KEY,
	AA.PERIOD_END_DATE_KEY,
	AA.REPORTED_MONTH,
	AA.INCIDENT_NUMBER,
	AA.DOCUMENTID,
	AA.CUSTOMER_NUMBER,
	AA.SLA_NAME,
	AA.CONTACT_COMPANY,
	AA.SERVICE_TYPE,
	AA.SERVICE_TYPE_DESCRIPTION,
    AA.SERVICE_COMPONENT,
	AA.M7_SERVICE_COMPONENT,
	AA.SERVICE_CATEGORY,
	AA.SERVICE_SUB_CATEGORY,
	AA.PRODUCT_NAME,
	AA.COMPLIANCE_TARGET,
	AA.TDJ_SLA_CONFIG,
	AA.TDJ_SLA_CONFIG_DESC,
	AA.CHM_CTM_CLUSTER,
	AA.ORIGINAL_CHM_CTM_CLUSTER,
	AA.SUPPORT_GROUP_FILTER,
	AA.LASTATUS,
	AA.LASTATUS_DESC,
	AA.SIGNED_UNSIGNED,
	AA.CONTRACT_STATUS,
    NULL AS [MPSS_CONTRACTTYPE],
    NULL AS [MPSS_STATUS],
	AA.TICKET_MET,
	1 AS M7_RESP_TICKET_MET,
	AA.TICKET_MISSED,
	AA.MET_OR_MISSED,
	AA.SLM_KEYWORD_SLA,
	AA.SLM_KEYWORD_OLA,
	AA.SLM_KEYWORD_UPC,
	AA.SLM_KEYWORD_RSP,
	AA.SUBMIT_DATE,
	AA.RESPONDED_DATE,
	AA.LAST_RESOLVED_DATE,
	AA.PARENTTOTALELAPSEDTIME,
	AA.PENDINGTIME,
	AA.ASSIGNEE,
	AA.ESTIMATED_RESOLUTION_DATE,
	AA.SOURCE_SYSTEM_CD,
	AA.ASSIGNED_GROUP,
	AA.PRIORITY_CD,
	AA.HELP_PRIORITY_DESC,
	AA.TIME_TAKEN,
	AA.MODIFIED_DATE,
	AA.TITLE,
	AA.TARGETHOURS,
	@DW_BATCH_ID AS BATCH_ID,
	GETDATE() AS CREATE_DT,
	AA.COORDINATOR,
	AA.STRUCTURE_LEVEL_1,
	AA.STRUCTURE_LEVEL_2,
	AA.STRUCTURE_LEVEL_3,
	AA.STRUCTURE_LEVEL_4,
    NULL AS [NEWSTARTDTE],
    NULL AS [NEWENDDTE],
    NULL AS [NEWSIGNEDDTE],
M5Previously_Reported_IND,
M5Previously_Reported_Month,
HPD_CI,
st.WA_NO,
st.VPN_Type,
AA.ASSIGNED_SUPPORT_COMPANY,
AA.ASSIGNED_SUPPORT_ORGANIZATION		

FROM (
SELECT  A.*,
DENSE_RANK() OVER (PARTITION BY A.REPORTED_MONTH, A.INCIDENT_NUMBER ORDER BY A.MODIFIED_DATE DESC) AS RANKING
FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1 A,
     (SELECT INCIDENT_NUMBER, REPORTED_MONTH, COUNT(*) CNT
		FROM BIExploitationLayer.DBO.TMP_SB_ITSM_LAST_INCIDENT10_FINAL_BUILD1
	WHERE REPORTED_MONTH = @REPORTED_MONTH
	GROUP BY INCIDENT_NUMBER, REPORTED_MONTH
	HAVING COUNT(*) > 2) B
WHERE A.REPORTED_MONTH = @REPORTED_MONTH
AND A.TITLE LIKE '%M7_TD%'
AND A.INCIDENT_NUMBER = B.INCIDENT_NUMBER
AND A.REPORTED_MONTH = B.REPORTED_MONTH
) AA
left JOIN [ZWSMCDBCLS01P01_CFI].ARSystem.dbo.GOV_CFG st ON AA.HPD_CI = st.End_Address
WHERE RANKING =1

--------------------------------------------------------------------------------------------------------------------

 UPDATE BIAUDITLAYER.[dbo].[DW_AUDIT_TRAIL]
 SET LOAD_END_DT = GETDATE(),
     LOAD_FINISHED = 'Y',
  MESSAGE_TRAIL = 'Finished with Load - FCT_REPORT_ITSM_LAST_INCIDENT10',
  RECORD_COUNT = @@ROWCOUNT
 WHERE BATCH_ID = @DW_BATCH_ID;

END TRY
BEGIN CATCH

 UPDATE BIAUDITLAYER.[dbo].[DW_AUDIT_TRAIL]
 SET LOAD_END_DT = GETDATE(),
     LOAD_FINISHED = 'Y',
  MESSAGE_TRAIL = 'Error with Load - Test FCT_REPORT_ITSM_LAST_INCIDENT10 - ' + ERROR_MESSAGE(),
  RECORD_COUNT = @@ROWCOUNT
 WHERE BATCH_ID = @DW_BATCH_ID;

END CATCH

----------------------------------------------------------------------------
